# Import the theme
theme: jekyll-theme-chirpy

# Language and Timezone
lang: en
timezone: America/New_York

# SEO Settings
title: Terminal Thoughts
tagline: Thoughts from the terminal — coding, creating, and growing
description: >-
  A developer blog by Phillip Green. Exploring tech, tools, and the creative side of code.
url: "https://phillipggreen.github.io"
baseurl: "/terminal-thoughts"

# Author & Social
github:
  username: phillipggreen

twitter:
  username: IcePickPhilly

social:
  name: Phillip Green
  email: contact@example.com
  links:
    - https://twitter.com/IcePickPhilly
    - https://github.com/phillipggreen
    - https://www.linkedin.com/in/phillipggreen

# Site Verification (optional)
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Analytics (optional)
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page view tracking (optional)
pageviews:
  provider:

# Color scheme
theme_mode: dark # or light, or leave empty for toggle

# CDN (optional)
cdn:

# Avatar and social preview (optional)
avatar:
social_preview_image:

# Global TOC and Comments
toc: true
comments:
  provider:

# Self-hosted static assets (optional)
assets:
  self_host:
    enabled:
    env:

# PWA (offline mode)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# Pagination
paginate: 10

# Markdown & syntax settings
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Jekyll Collections
collections:
  tabs:
    output: true
    sort_by: order

# Layout Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# SASS & HTML Compression
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Jekyll Archives for tags/categories
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Exclude files from build
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
